language: c
os: linux
dist: xenial

install:
  # Prerequisites for documentation
  - "sudo apt-get install texinfo texlive-latex-base latex2html"

# try to build
script: ./configure && make && make check && make distcheck

compiler:
  - clang
  - gcc
