name: cooljeanius/gaa
on:
  push:
    branches:
      - "**/*"
    tags:
      - "v1.6.6*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get update
    - run: sudo apt-get install texinfo texlive-latex-base latex2html
    - run: "./configure CC=${{ matrix.compiler }} && make && make check && make distcheck"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: gzipped_tarfile-${{ matrix.compiler }}
        path: gaa-1.6.6.tar.gz
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
